<?php
define ('USERNAME', 'custom_username');
define ('CONTEXT_ID', 'context_id');
define ('INSTANCE_ID', 'resource_link_id');
define ('LAUNCH_PRESENTATION_LOCALE', 'launch_presentation_locale');
define ('CUSTOM_LANG', 'custom_lang_id');
define ('LANG', 'lang');
define ('AUTHORIZATION_KEY_OKI' , /*'uocPHP_tandem'*/'uocPHP_aws_amazon');
define ('AUTHORIZATION_KEY_FIELD_OKI' , 'authorization_key');
define ('CONTAINER_FIELD_OKI', 'container');
define ('INSTANCEID_FIELD_OKI', 'instanceId');
define ('PROVIDER_PREFIX_OKI', 'provider_');
define ('PROVIDER_PREFIX_OKI_COMPONENTS', 'provider_components_');
define ('SESSION_ID_FIELD_OKI' , 's');
define ('SESSION_ID_FIELD' , 'custom_sessionid');
define ('ADMINISTRATOR_ROLE', 'administrator');
define ('LEARNER_ROLE', 'learner');
define ('DOMAIN_PREFIX', 'DOMAIN.');
define ('NAME_OPTION' , 'student_option_');
define ('COURSE_ID', 'course_id');
define ('EMAIL', 'email');
define ('FULLNAME', 'fullname');
define ('USER_ID', 'user_id');
define ('INSTANCEC2ID', 'InstanceID');
define ('IS_INSTRUCTOR', 'is_instructor');
define('STOPSELECT', 'stop_selected');
define('STARTSELECT', 'start_selected');
define ('SALVA_DADES', 'save');
define ('HOURS_AUTOSTOP', 24);
define ('EMAILOKI', 'email');
define ('FULLNAMEOKI', 'fullName');
define ('FIRSTNAMEOKI', 'firstName');
define ('SURNAMEOKI', 'surName');
define ('IMAGEOKI', 'photo');
define ('OATUH_CONSUMER_KEY', 'oauth_consumer_key');
define ('DELIMITER', ':');
define ('CURRENT_USER', 'current_user');
if (!defined('HTTPATTRIBUTEKEY_OSIDCONTEXT'))
	define ('HTTPATTRIBUTEKEY_OSIDCONTEXT', 'osid_context');
define ('OKIBUSPHP_COMPONENTS', 'okibusPHP_components');
define ('OKIBUSPHP_OKIBUSCLIENT', 'okibusPHP_okibusClient');
define ('ID_RESOURCE', 'resource_link_id');
define ('CURRENT_TANDEM', 'current_tandem');
define ('TANDEM_NUMBER_FIELD', 'node');
define ('TANDEM_NUMBER_OF_NODE_FIELD', 'number');
define ('TANDEM_COURSE_FOLDER', 'course_folder');
define ('LTI_CONTEXT', 'lti_context_obj');
define ('LIS_RESULT_SOURCEID', 'lis_result_sourceid');